configure nosetests.

diff --git a/utils/git/pre-commit b/utils/git/pre-commit
--- a/utils/git/pre-commit
+++ b/utils/git/pre-commit
@@ -29,8 +29,22 @@ function call_flake8 {
     return 0
 }
 
-EXIT_STATUS=0
-test_dependencies || (EXIT_STATUS=1 && exit $EXIT_STATUS)
-call_flake8 || EXIT_STATUS=1
+function test_coverage {
+    rm -fr .coverage cover
+    ./setup.py nosetests
+    COVERAGE_EXIT=$?
 
-exit $EXIT_STATUS
+    if [[ "${COVERAGE_EXIT}" == 0 ]]; then
+      printf "\033[42mCOVERAGE SUCCEEDED\033[0m\n"
+    else
+      printf "\033[41mCOVERAGE FAILED:\033[0m Fix coverage errors and try again\n"
+      return 1
+    fi
+
+    return 0
+}
+
+cd $BASE_PATH
+test_dependencies &&
+call_flake8 &&
+test_coverage
diff --git a/utils/git/pre-push b/utils/git/pre-push
--- a/utils/git/pre-push
+++ b/utils/git/pre-push
@@ -29,11 +29,38 @@ function call_flake8 {
     return 0
 }
 
-EXIT_STATUS=0
-cd $BASE_PATH
-python3 setup.py bdist || (EXIT_STATUS=1 && exit $EXIT_STATUS)
-python3 setup.py sdist || (EXIT_STATUS=1 && exit $EXIT_STATUS)
-test_dependencies || (EXIT_STATUS=1 && exit $EXIT_STATUS)
-call_flake8 || EXIT_STATUS=1
+function test_coverage {
+    rm -fr .coverage cover
+    ./setup.py nosetests
+    COVERAGE_EXIT=$?
 
-exit $EXIT_STATUS
+    if [[ "${COVERAGE_EXIT}" == 0 ]]; then
+      printf "\033[42mCOVERAGE SUCCEEDED\033[0m\n"
+    else
+      printf "\033[41mCOVERAGE FAILED:\033[0m Fix coverage errors and try again\n"
+      return 1
+    fi
+
+    return 0
+}
+
+function do_release {
+    rm -fr build dist doc/build
+    python3 setup.py create_release
+    RELEASE_EXIT=$?
+
+    if [[ "${RELEASE_EXIT}" == 0 ]]; then
+      printf "\033[42mRELEASE SUCCEEDED\033[0m\n"
+    else
+      printf "\033[41mRELEASE FAILED:\033[0m Fix release errors and try again\n"
+      return 1
+    fi
+
+    return 0
+}
+
+cd $BASE_PATH
+test_dependencies &&
+call_flake8 &&
+test_coverage &&
+do_release
